version: '3.1'

services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strongpass
    volumes:
      - dbdata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: strongpass
      ME_CONFIG_MONGODB_URL: mongodb://root:strongpass@mongodb:27017

  app:
    build: .
    container_name: ozmap-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://root:strongpass@mongodb:27017
    depends_on:
      - mongodb

volumes:
  dbdata:
